### ISSUE TITLE
dataServer EADDRINUSE Error

### ISSUE THREAD

**Issue by joespina** [trs/ftp-srv#98]
Hi there!

Using `ftp-srv` on a project and I am getting this error:
    
    ftpServer.on('client-error', (data) => {

        // data.context
        context:"dataServer"

        // data.error
        address:"192.168.0.120"
        code:"EADDRINUSE"
        errno:"EADDRINUSE"
        port:8080
        syscall:"listen"

    });

I have 2 CCTV cameras that FTP snapshots of CCTV Footage to `ftp-srv` every second. This is not a persistent error, it just happens every now and then, maybe once every few seconds? But every time it happens, there is a 10 second gap for ftp-srv to recover. I really can't pinpoint when or why this is happening though. Tried googling, failed.

Here is the bulk of the code, if it helps:

    const ftpServer = new FtpSrv('ftp://192.168.0.120:9876', {
      pasv_range:8080
    });
     
    ftpServer.on('login', (data, resolve, reject) => {

      resolve({root: 'F:/path/to/ftp/root'});

      data.connection.on('STOR', (error, fileName) => {
        var filePath = data.connection.fs.cwd;
        if (error === null) {
          mainWindow.webContents.send('cctvSnapshot', {
            filePath: filePath,
            fileName: fileName
          });
        }
      });

    });

Any idea how to fix this?

**Comment by joespina** [comment]
I tried to dig deeper here and I found out that the cause of this issue is because of simultaneous connections? To test I turned off 1 of the 2 CCTV Cameras and then **poof** the error went away.

**Comment by trs** [comment]
I think this might be caused by how I'm choosing which port to use in a passive connection.
It always starts from the min pasv range and works it's way up.
If 2 connections attempt to get a passive connection at the same time, I can see them both being assigned the same port.

I'm working on some [major changes](https://github.com/trs/ftp-srv/pull/99) which includes a generator for pasv ports so they are always incrementing.

But some more testing will be needed to see if this is the cause.
